# Generated by Django 5.0.2 on 2024-02-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_image',
            field=models.ImageField(null=True, upload_to='pet'),
        ),
    ]
